In [1]:
import numpy as np

arr = np.array([1,5,3,4,5])

arr

array([1, 5, 3, 4, 5])

In [2]:
from time import process_time

In [3]:
python_list =[i for i in range(10)]
print(python_list)

start_time = process_time()
print(start_time)

python_list = [i+5*2 for i in python_list]

end_time = process_time()
print(end_time)

print(round((end_time - start_time),9))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
0.734375
0.734375
0.0


In [22]:
np_array = np.array([i for i in range(100000)])

start_time = process_time()
print(start_time)

np_array += 50000

end_time= process_time()
print(end_time)

print(round((end_time - start_time),9))

3.65625
3.65625
0.0


### Numpy Arrays

In [25]:
#list 
list = [1,2,3,4,5]
print(list)
type(list)

[1, 2, 3, 4, 5]


list

In [26]:
#list 
np_array = np.array([1,2,3,4,5])   # np works as matrixes
print(np_array)
type(np_array)

[1 2 3 4 5]


numpy.ndarray

In [27]:
# Creating one dimension array
a = np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [28]:
a.shape

(5,)

In [32]:
# 2 dimensional array
b = np.array([(1,2,3,4),(5,6,7,8)])
print(b)
b

[[1 2 3 4]
 [5 6 7 8]]


array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [33]:
b.shape

(2, 4)

In [34]:
c= np.array([(1,2,3,4),(5,6,7,8)], dtype=float)
c

array([[1., 2., 3., 4.],
       [5., 6., 7., 8.]])

### Initial Placeholder in numpy arrays

In [38]:
# create a numpy array of zeroes
x= np.zeros((4,5))
x

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [39]:
# create a numpy array of ones
y = np.ones((3,3))
y

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [40]:
# array of a particular value
z= np.full((5,4),5)
z

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

In [43]:
# create an identity matrix
a = np.eye(5)
print(a)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [44]:
# create a numpy array with random values
b = np.random.random((3,4))
b

array([[0.89699162, 0.54069798, 0.59320695, 0.87712957],
       [0.28624829, 0.37885942, 0.0599298 , 0.57609183],
       [0.27001754, 0.22558648, 0.73588404, 0.17409806]])

In [47]:
# random intergers values array within a specific range
r_int = np.random.randint(10,150,(3,5))
r_int

array([[ 24,  92,  52, 129,  46],
       [ 65,  82, 131,  92,  82],
       [144,  54, 139,  34, 146]])

In [48]:
r_int

array([[ 24,  92,  52, 129,  46],
       [ 65,  82, 131,  92,  82],
       [144,  54, 139,  34, 146]])

In [53]:
# array of evenly spaced values -- > specifying the no. of values
arr = np.linspace(10,30,8)    # getting evenly spaced values between 10 and 30
print(arr)
process_time()

[10.         12.85714286 15.71428571 18.57142857 21.42857143 24.28571429
 27.14285714 30.        ]


5.375

In [54]:
# array of evenly spaced values --> specifying the step value
arr_spc = np.arange(10,30,5)   ## getting the value at the 5 step starting with 10 and end at 30

In [55]:
arr_spc

array([10, 15, 20, 25])

In [57]:
# convert a list to numpy array
list2 = [10,20,30,40,50]

np_array = np.asarray(list2)
print(np_array)

[10 20 30 40 50]


In [61]:
# convert tuple to numpy array
tup = (1,2,3,52)
type(tup)

np_arr = np.asarray(tup)
print(np_arr)
type(np_arr)

[ 1  2  3 52]


numpy.ndarray

In [94]:
# convert the datatype
arr = np.array([1, 0, 3])

newarr = arr.astype(bool)

print(newarr)
print(newarr.dtype)

[ True False  True]
bool


### Analysing a numpy array

In [62]:
arr = np.random.randint(10,99,(5,5))
print(arr)

[[73 87 69 21 72]
 [71 89 28 29 43]
 [73 83 19 29 16]
 [12 44 74 56 64]
 [65 39 79 68 42]]


In [63]:
# array shape/dimensions
arr.shape

(5, 5)

In [64]:
# array dimension
arr.ndim

2

In [66]:
# number of elements in the array/matrix
arr.size

25

In [68]:
# checking the data type of values in array
arr.dtype

dtype('int32')

### Mathematical Operations on Numpy array

In [69]:
# addition in list
l1 = [1,2,3,4]
l2 = [5,6,7,8]

print(l1+l2)  # concatenate the lists

[1, 2, 3, 4, 5, 6, 7, 8]


In [13]:
# addition in numpy array
a = np.random.randint(0,10,(3,3))
b = np.random.randint(10,20,(3,3))
print(a)
print(b)

[[8 6 4]
 [3 5 6]
 [0 5 9]]
[[17 15 11]
 [11 18 18]
 [19 16 19]]


In [14]:
print(a + b)

[[25 21 15]
 [14 23 24]
 [19 21 28]]


In [15]:
print(a-b)

[[ -9  -9  -7]
 [ -8 -13 -12]
 [-19 -11 -10]]


In [16]:
print(a/b)

[[0.47058824 0.4        0.36363636]
 [0.27272727 0.27777778 0.33333333]
 [0.         0.3125     0.47368421]]


In [17]:
print(np.add(a,b))

[[25 21 15]
 [14 23 24]
 [19 21 28]]


In [23]:
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,a))
print("---------------------")
print(np.concatenate((a,b)))
print("---------------------")
print(np.concatenate((a,b),axis=1))
print("---------------------")
print(np.stack((a,b),axis=1))


[[ -9  -9  -7]
 [ -8 -13 -12]
 [-19 -11 -10]]
[[136  90  44]
 [ 33  90 108]
 [  0  80 171]]
[[ 1.  1.  1.]
 [ 1.  1.  1.]
 [nan  1.  1.]]
---------------------
[[ 8  6  4]
 [ 3  5  6]
 [ 0  5  9]
 [17 15 11]
 [11 18 18]
 [19 16 19]]
---------------------
[[ 8  6  4 17 15 11]
 [ 3  5  6 11 18 18]
 [ 0  5  9 19 16 19]]
---------------------
[[[ 8  6  4]
  [17 15 11]]

 [[ 3  5  6]
  [11 18 18]]

 [[ 0  5  9]
  [19 16 19]]]


C:\Users\Mayank\AppData\Local\Temp\ipykernel_24332\3856054285.py:3: RuntimeWarning: invalid value encountered in divide
  print(np.divide(a,a))


### Array Manipulation

In [78]:
arr = np.random.randint(0,35,(2,4))

print(arr)
print(arr.shape)
print(arr.size)
print(arr.dtype)
print(arr.ndim)

[[33  0  9 31]
 [ 1 26  6 32]]
(2, 4)
8
int32
2


In [80]:
# transpose the array
trans = np.transpose(arr)
print(trans)
print(trans.shape)

[[33  1]
 [ 0 26]
 [ 9  6]
 [31 32]]
(4, 2)


In [81]:
trans2 = arr.T
trans2

array([[33,  1],
       [ 0, 26],
       [ 9,  6],
       [31, 32]])

In [83]:
# reshaping a array
a = np.random.randint(0,58,(5,4))
print(a)
a.shape

[[49 26  1 15]
 [31 55 19 25]
 [16 49 18 24]
 [26  5  8 21]
 [30 55  2 37]]


(5, 4)

In [85]:
b = a.reshape(2,10)
b

array([[49, 26,  1, 15, 31, 55, 19, 25, 16, 49],
       [18, 24, 26,  5,  8, 21, 30, 55,  2, 37]])

In [98]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(2, 3, 2)

print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [86]:
arr = np.array([1, 2, 3, 4])

print(arr[2] + arr[3])

7


In [88]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5:3])

[2 5]


In [89]:
import numpy as np

a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [93]:
#Create an array with data type 4 bytes integer:

import numpy as np

arr = np.array([1, 2, 3, 4], dtype='i4')

print(arr)
print(arr.dtype)

[1 2 3 4]
int32


In [95]:
# copy vs view
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42

print(arr)
print(x)


[42  2  3  4  5]
[1 2 3 4 5]


In [96]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
x[0] = 31

print(arr)
print(x)

[31  2  3  4  5]
[31  2  3  4  5]


In [97]:
# copies owns the data, and views does not own the data, but how can we check this?

# Every NumPy array has the attribute base that returns None if the array owns the data.

# Otherwise, the base  attribute refers to the original object.

arr = np.array([1, 2, 3, 4, 5])

x = arr.copy()
y = arr.view()

print(x.base)
print(y.base)

None
[1 2 3 4 5]


In [99]:
# array - Iteration on array
arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
  print(x)

[1 2 3]
[4 5 6]


In [4]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])

for x in arr:
    print(x)

[1 2 3]
[4 5 6]
[7 8 9]


In [5]:
# 2d array
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])

for x in arr:
    print(x)
    for y in x:
        print(y)

[1 2 3]
1
2
3
[4 5 6]
4
5
6
[7 8 9]
7
8
9


In [6]:
# 3d array
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in arr:
  print("x represents the 2-D array:")
  print(x)



x represents the 2-D array:
[[1 2 3]
 [4 5 6]]
x represents the 2-D array:
[[ 7  8  9]
 [10 11 12]]


In [7]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in arr:
    print(x)
    for y in x:
        print("y is",y)
        for z in y:
            print(z)

[[1 2 3]
 [4 5 6]]
y is [1 2 3]
1
2
3
y is [4 5 6]
4
5
6
[[ 7  8  9]
 [10 11 12]]
y is [7 8 9]
7
8
9
y is [10 11 12]
10
11
12


In [8]:
# 3d array - Iterating Arrays Using nditer()
# insteed of for loop - for iteration, use nditer() for array with high dimensions

arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

for x in np.nditer(arr):
  print(x)

1
2
3
4
5
6
7
8


In [11]:
arr = np.array([[1,2,3,4,5],[6,7,8,9,1]])

for x in arr:
    print(x)
    
for x in np.nditer(arr[:,::2]):
    print(x)

[1 2 3 4 5]
[6 7 8 9 1]
1
3
5
6
8
1


In [12]:
arr = np.array([1, 2, 3])

for idx, x in np.ndenumerate(arr):
  print(idx, x)

(0,) 1
(1,) 2
(2,) 3


### Split in array

In [24]:
# splitting the array
arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)

print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [25]:
arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 4)

print(newarr)

[array([1, 2]), array([3, 4]), array([5]), array([6])]


In [26]:
# splitting 2D Array
arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])

newarr = np.array_split(arr, 3)

print(newarr)

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]


In [27]:
arr

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [28]:
# split according to the row
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.array_split(arr, 3, axis=1)

print(newarr)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


In [29]:
newarr = np.hsplit(arr, 3)
newarr

[array([[ 1],
        [ 4],
        [ 7],
        [10],
        [13],
        [16]]),
 array([[ 2],
        [ 5],
        [ 8],
        [11],
        [14],
        [17]]),
 array([[ 3],
        [ 6],
        [ 9],
        [12],
        [15],
        [18]])]

In [30]:
newarr = np.vsplit(arr, 3)
newarr

[array([[1, 2, 3],
        [4, 5, 6]]),
 array([[ 7,  8,  9],
        [10, 11, 12]]),
 array([[13, 14, 15],
        [16, 17, 18]])]

### Searching the array no. index

In [33]:
array= np.array([1,2,3,4,5,6,8,9,11,25,36])
x= np.where(array==4)
y= np.where(array%2 ==0)

In [34]:
print("X is",x)
print("Y is", y)

X is (array([3], dtype=int64),)
Y is (array([ 1,  3,  5,  6, 10], dtype=int64),)


In [38]:
 # similar as where but if you find a no. that is not in array then it will retturn the nearest index
x = np.searchsorted(array, 9) 
x

7

### Sorting in array

In [39]:
# 2D array sorting
arr = np.array([[3, 2, 4], [5, 0, 1]])

print(np.sort(arr))

[[2 3 4]
 [0 1 5]]


In [40]:
arr = np.array([41, 42, 43, 44])

# Create an empty list
filter_arr = []

# go through each element in arr
for element in arr:
  # if the element is higher than 42, set the value to True, otherwise False:
  if element > 42:
    filter_arr.append(True)
  else:
    filter_arr.append(False)

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)


[False, False, True, True]
[43 44]
